version: 2.1
jobs:
  Client-Test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - client-yarn-packages-{{ checksum "client/yarn.lock" }}
        command: cd client && yarn install --frozen-lockfile
      - save_cache:
        name: Save Yarn Package Cache
        key: client-yarn-packages-{{ checksum "client/yarn.lock" }}
        paths:
          - ~/.cache/yarn
        command: client && yarn test