version: 2.1
jobs:
  Client-Test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - client-yarn-packages-{{ checksum "client/yarn.lock" }}
      - run:
          command: cd client && yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: client-yarn-packages-{{ checksum "client/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: cd client && yarn test
  Server-Test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache in Server
          keys:
            - server-yarn-packages-{{ checksum "server/yarn.lock" }}
      - run:
          command: cd server && yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache in Server
          key: server-yarn-packages-{{ checksum "server/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: cd server && yarn test

  # Run-With-Node:
  #   docker:
  #     - image: circleci/node:latest
  #   steps:
  #     - run:
  #         name: Running In A Container With Node
  #         command: |
  #           node -v
  # Now-Complete:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
  #         name: Approval Complete
  #         command: |
  #           echo 'Do work once the approval has completed'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Client-Test
      - Server-Test
        # - Second-Job:
        #     requires:
        #       - First-Job
        # - Run-With-Node:
        #     requires:
        #       - First-Job
        # - Hold-For-Approval:
        #     type: approval
        #     requires:
        #       - Run-With-Node
        #       - Second-Job
        # - Now-Complete:
        #     requires:
        #       - Hold-For-Approval
